command:
  - python
  - run_app.py
env:
  - name: SERVE_STATIC
    value: "true"
  - name: ENABLE_DOCS
    value: "false"
  - name: OTEL_TRACES_SAMPLER
    value: "always_on"
  - name: OTEL_PYTHON_LOG_CORRELATION
    value: "true"
