sonar.projectKey=Paldom_databricks-apps-fastapi-starter
sonar.organization=dpal

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests
sonar.exclusions=**/notebooks/**,frontend/src/shared/api/generated/**,frontend/src/mocks/**,frontend/src/**/*.test.*,frontend/src/**/*.stories.*,frontend/src/test/**
sonar.cpd.exclusions=frontend/src/shared/api/generated/**,backend/alembic/**
sonar.python.version=3.11
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.qualitygate.wait=true
