resources:
  apps:
    fastapi_app:
      name: ${var.app_name}
      description: "FastAPI RAG starter deployed from bundle"
      source_code_path: ./backend
      config: ${var.app_config}
      user_api_scopes:
        - files.files
      permissions:
        - level: CAN_USE
          group_name: users
      resources:
        - name: serving-endpoint
          serving_endpoint:
            name: ${resources.model_serving_endpoints.starter_endpoint.name}
            permission: CAN_QUERY
        - name: app-job
          job:
            id: ${resources.jobs.rag_ingestion_job.id}
            permission: CAN_MANAGE_RUN
        - name: uc-volume
          uc_securable:
            securable_type: VOLUME
            securable_full_name: ${var.volume_full_name}
            permission: WRITE_VOLUME
        - name: lakebase-db
          database:
            name: ${resources.database_instances.lakebase_oltp.name}
            permission: USE
        - name: knowledge-assistant
          serving_endpoint:
            name: ${var.knowledge_assistant_endpoint_name}
            permission: CAN_QUERY
        - name: serving-agent
          serving_endpoint:
            name: ${var.serving_agent_endpoint}
            permission: CAN_QUERY
        - name: experiment
          experiment:
            experiment_id: ${resources.experiments.app_experiment.id}
            permission: CAN_MANAGE
