#!/usr/bin/env bash
# One-time workspace preparation for a first deploy (see README "Deploy").
#
# Detects a writable catalog, derives the dev-mode schema name, creates the
# /Shared experiments folder, builds the frontend if needed, and writes the
# bundle-variable overrides to .bundle-vars.<target>.sh (BUNDLE_VAR_* env
# vars, picked up automatically by `databricks bundle`).
#
# Usage: scripts/bootstrap-workspace.sh [-p PROFILE] [-t TARGET] [-c CATALOG]
set -euo pipefail

PROFILE="${DATABRICKS_CONFIG_PROFILE:-DEFAULT}"
TARGET="dev"
CATALOG="${CATALOG:-}"
while getopts "p:t:c:" opt; do
  case $opt in
    p) PROFILE="$OPTARG" ;;
    t) TARGET="$OPTARG" ;;
    c) CATALOG="$OPTARG" ;;
    *) echo "usage: $0 [-p profile] [-t target] [-c catalog]" >&2; exit 2 ;;
  esac
done

say() { printf '\033[1m==> %s\033[0m\n' "$*"; }

say "Checking authentication (profile: $PROFILE)"
USER_NAME=$(databricks current-user me --profile "$PROFILE" -o json | python3 -c 'import json,sys; print(json.load(sys.stdin)["userName"])')
say "Authenticated as $USER_NAME"

say "Creating experiments folder /Shared/databricks-apps-fastapi-starter"
databricks workspace mkdirs /Shared/databricks-apps-fastapi-starter --profile "$PROFILE"

if [ -z "$CATALOG" ]; then
  say "Detecting a usable catalog (pass -c to override)"
  CATALOG=$(databricks catalogs list --profile "$PROFILE" -o json | python3 -c '
import json, sys
skip = {"system", "samples", "hive_metastore", "main"}
cats = [c["name"] for c in json.load(sys.stdin) if c["name"] not in skip]
print(cats[0] if cats else "main")')
fi
say "Using catalog: $CATALOG"

# The dev target prefixes bundle-declared schemas with dev_<user>_.
SAFE_USER=$(printf '%s' "$USER_NAME" | python3 -c 'import re,sys; print(re.sub(r"[^a-zA-Z0-9]", "_", sys.stdin.read().split("@")[0]))')
if [ "$TARGET" = "dev" ]; then SCHEMA="dev_${SAFE_USER}_starter_rag"; else SCHEMA="starter_rag"; fi
say "RAG schema will be: $CATALOG.$SCHEMA"

if [ ! -f backend/public/index.html ]; then
  say "Building frontend (backend/public is empty)"
  (cd frontend && npm ci && npm run build)
else
  say "Frontend build present (backend/public)"
fi

say "Probing for a Responses-API-passthrough-capable chat model"
TOKEN=$(databricks auth token --profile "$PROFILE" -o json | python3 -c 'import json,sys; print(json.load(sys.stdin)["access_token"])')
HOST=$(python3 - "$PROFILE" <<'PY'
import configparser, os, sys
cfg = configparser.ConfigParser()
cfg.read(os.path.expanduser("~/.databrickscfg"))
print(cfg[sys.argv[1]]["host"].rstrip("/"))
PY
)
AGENT_MODEL=""
for m in databricks-gpt-5-4-mini databricks-gpt-5-5 databricks-claude-sonnet-4 databricks-meta-llama-3-3-70b-instruct; do
  code=$(curl -s -o /dev/null -w '%{http_code}' -m 20 -X POST     -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json"     "$HOST/serving-endpoints/responses"     -d "{\"model\":\"$m\",\"input\":\"ok\",\"max_output_tokens\":16}") || code=000
  if [ "$code" = "200" ]; then AGENT_MODEL="$m"; break; fi
done
if [ -n "$AGENT_MODEL" ]; then
  say "Serving agent upstream: $AGENT_MODEL"
else
  say "WARNING: no passthrough-capable model found; serving agent deploy may fail (see docs/deployment.md)"
fi

VARS_FILE=".bundle-vars.${TARGET}.sh"
say "Writing $VARS_FILE"
cat > "$VARS_FILE" <<VARS
# Generated by scripts/bootstrap-workspace.sh — source before bundle commands:
#   source $VARS_FILE && databricks bundle deploy -t $TARGET -p $PROFILE
export BUNDLE_VAR_rag_catalog_name="$CATALOG"
export BUNDLE_VAR_knowledge_upload_root="/Volumes/$CATALOG/$SCHEMA/uploads/knowledge/uploads"
export BUNDLE_VAR_rag_checkpoint_root="/Volumes/$CATALOG/$SCHEMA/uploads/system/checkpoints/rag_ingestion"
export BUNDLE_VAR_rag_raw_table_name="$CATALOG.$SCHEMA.rag_raw_documents"
export BUNDLE_VAR_rag_chunk_table_name="$CATALOG.$SCHEMA.rag_document_chunks"
export BUNDLE_VAR_rag_summary_table_name="$CATALOG.$SCHEMA.rag_document_summaries"
export BUNDLE_VAR_serving_agent_uc_model_name="$CATALOG.$SCHEMA.serving_agent"
${AGENT_MODEL:+export BUNDLE_VAR_serving_agent_chat_model="$AGENT_MODEL"}
VARS

say "Done. Next:"
echo "  source $VARS_FILE"
echo "  databricks bundle deploy -t $TARGET -p $PROFILE"
echo "  databricks bundle run  -t $TARGET -p $PROFILE fastapi_app"
