name: Load test

on:
  workflow_dispatch:
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -e .[dev]
  load-test:
    needs: install
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST || 'localhost' }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID || 'dummy' }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET || 'dummy' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install uv
          uv pip install -e .[dev]
      - name: Start app
        run: uvicorn main:app & sleep 5
      - name: Run Locust
        run: |
          HOST=http://localhost:8000 \
          DATABRICKS_HOST="$DATABRICKS_HOST" \
          DATABRICKS_CLIENT_ID="$DATABRICKS_CLIENT_ID" \
          DATABRICKS_CLIENT_SECRET="$DATABRICKS_CLIENT_SECRET" \
          poetry run locust -f tests/performance/locustfile.py --headless -u 50 -r 10 -t 60s --csv=locust --csv-full-history --html=locust-report.html
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: locust-results
          path: |
            locust_stats_history.csv
            locust-report.html

