name: Snyk Security (CI)

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write   # needed for SARIF upload
  actions: read

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Python toolchain to restore virtual-env quickly
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # install project deps so Snyk can inspect them
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install Snyk CLI
      - name: Snyk – Install CLI
        uses: snyk/actions/setup@v1
        with:
          version: "latest"
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Run the scan and output SARIF (continue-on-error so SARIF still uploads)
      - name: Snyk – Open Source scan
        run: snyk test --sarif-file-output=snyk.sarif --severity-threshold=high
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Optionally scan IaC manifests (databricks.yml, app.yaml, etc.)
      - name: Snyk – IaC scan
        run: snyk iac test .
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Upload results to GitHub Security tab
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
